### ISSUE TITLE
semantic info

### ISSUE THREAD

**Issue by tsuyoshicho** [tsuyoshicho/github-config#3]
https://github.com/zeke/semantic-pull-requests

in `.github` dir.

```yaml:semantic.yml
titleOnly: true
allowMergeCommits: true
allowRevertCommits: true
# see https://github.com/zeke/semantic-pull-requests 
```

**Comment by tsuyoshicho** [comment]
and more auto-assign

in `.github` dir, `auto_assign-issues.yml`.

```yaml:auto_assign-issues.yml 
addAssignees: true
assignees:
  - tsuyoshicho
```
